name: Deploy to AWS ECS

on:
  push:
    branches:
      - main  

jobs:
  scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Scan with Snyk
        id: snyk-scan
        uses: snyk/actions/node@master
        with:
          args: --file=package.json --sarif-file-output=snyk.sarif || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true  

      - name: Convert SARIF to Text using jq
        run: |
          jq -r '.runs[].results[] | "Rule: \(.ruleId) - Severity: \(.level) - Message: \(.message.text)"' snyk.sarif > snyk_report.txt || true

      - name: Upload Snyk Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk_report.txt

  build:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    needs: scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push image to Amazon ECR
        env:
          ECR_REPOSITORY: react-frontend
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG


  image-scan:
    name: Scan Image with Trivy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget curl jq
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv ./bin/trivy /usr/local/bin/trivy
          sudo chmod +x /usr/local/bin/trivy
          echo "Trivy installation completed."
          trivy --version  # Verify installation

      - name: Pull Image from ECR
        env:
          ECR_REPOSITORY: flask-backend
          IMAGE_TAG: latest
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "Pulling image: $IMAGE_URI"
          docker pull $IMAGE_URI  # Pull image from ECR before scanning
          
      - name: Scan Image with Trivy
        env:
          ECR_REPOSITORY: flask-backend
          IMAGE_TAG: latest
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "Scanning image with Trivy: $IMAGE_URI"
          trivy image --exit-code 0 --severity HIGH,CRITICAL $IMAGE_URI > trivy_report.txt
          cat trivy_report.txt
      
      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy_report.txt

  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster applicationclusters --service frontend-service --force-new-deployment --desired-count 1 --task-definition frontend-td:2
